name: Cloudsmith Push Docker Image
on: push
jobs:
  push:
    runs-on: ubuntu-latest
    name: Python Push
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read  # This is required for actions/checkout
    steps:
    - name: Get OIDC token
      run: |
        value=$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL" | jq '.value')
          echo "$value"
          token=$(curl -X POST -H "Content-Type: application/json" -d "{\"oidc_token\":$value, \"service_slug\":\"github-actions-demo\"}" https://api.cloudsmith.io/openid/jake-org/ | jq -r '.token')
          echo "BTOKEN=Bearer $token" >> $GITHUB_ENV
          echo "OIDC_TOKEN=$token" >> $GITHUB_ENV
    - uses: actions/checkout@v2
    - name: Push
      id: push
      uses: cloudsmith-io/action@master
      with:
        sub: '077de440303cade48c15d18d4ef6523edd9b8579' # subject, auth token
        api-key: $OIDC_TOKEN
        command: "push"
        format: "python"
        owner: 'jake-org'                               # Your Cloudsmith account name or org name (namespace) 
        repo: 'cloudsmith-actions-demo'                 # Your Cloudsmith Repository name (slug)
        republish: 'true'                               # needed ONLY if version is not changing
        file: example-package.tar.gz                    # Python package filename
